In [88]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd

In [126]:
path = os.getcwd() + '/data_input/2021-3-25/gold/0_gold_test_ppp_1s_bin8/run1'

In [231]:
files = sorted([i for i in os.listdir(path) if '.txt' in i and 'ps' not in i and 'powers' not in i])

data = [i for i in files if '_bg' not in i]
data_indices = [str(i) for i in np.arange(len(data))]

bkg = [i for i in files if '_bg' in i]
bkg_indices = [str(i) for i in np.arange(len(bkg))]

col_names = ['wl','1','2','cts']

ef=pd.DataFrame()
for i in bkg:
    i_name = i.rstrip('.txt')
    df = pd.read_csv(path+'/'+i, sep='\t', names=col_names)
    df.drop(columns=['1','2'], inplace=True)
    df['wn'] = 10000000/df['wl'] - 12579
    df.sort_values(by='wn',inplace=True)
    df.columns = pd.MultiIndex.from_product([[i_name], df.columns])
    df = df.reset_index(drop=True)
    ef = pd.concat([ef,df],axis=1)

ef.loc[:,ef.columns.get_level_values(1)=='wn'].head(50)

,2600_bg,2800_bg,3000_bg,3100_bg,3300_bg,3500_bg,3700_bg
,wn,wn,wn,wn,wn,wn,wn
0,3081.652454,2960.894795,2841.961404,2724.858103,2609.519909,2495.907214,2383.981584
1,3087.197203,2966.330183,2847.313898,2730.106163,2614.689149,2500.976656,2388.976015
2,3092.745880,2971.769374,2852.670108,2735.381276,2619.861909,2506.072265,2393.973782
3,3098.298488,2977.236573,2858.030039,2740.636557,2625.038193,2511.148547,2398.974888
4,3103.855032,2982.683401,2863.393695,2745.918931,2630.218003,2516.251034,2403.979335
5,3109.415517,2988.158278,2868.761079,2751.181448,2635.401344,2521.334170,2409.009592
6,3114.979946,2993.612757,2874.132195,2756.471098,2640.588219,2526.443549,2414.020749
7,3120.548324,2999.095329,2879.507048,2761.740866,2645.778632,2531.556386,2419.035257
8,3126.120655,3004.557477,2884.885641,2767.037806,2650.972586,2536.649837,2424.053121
9,3131.696942,3010.047759,2890.267979,2772.338406,2656.170085,2541.769587,2429.074344
10,3137.277191,3015.541910,2895.654064,2777.619087,2661.394360,2546.892806,2434.121468
11,3142.861406,3021.015600,2901.067865,2782.927000,2666.598977,2552.019498,2439.149434
12,3148.449590,3026.517487,2906.461474,2788.238584,2671.807149,2557.149666,2444.180768
13,3154.066501,3032.023256,2911.858844,2793.553842,2677.042155,2562.283315,2449.238059
14,3159.662654,3037.532911,2917.283991,2798.872779,2682.257467,2567.420446,2454.276157
15,3165.262791,3043.046457,2922.688909,2804.195397,2687.499651,2572.561065,2459.340248
16,3170.891719,3048.563897,2928.121646,2809.521702,2692.722116,2577.705175,2464.407753
17,3176.499851,3054.085236,2933.534128,2814.851696,2697.971493,2582.852778,2469.456028
18,3182.136819,3059.610478,2938.974470,2820.185383,2703.201126,2588.003880,2474.530354
19,3187.752963,3065.139627,2944.394532,2825.522768,2708.457711,2593.158482,2479.608103
20,3193.397988,3070.672687,2949.842496,2830.863854,2713.717914,2598.339625,2484.666587
21,3199.047056,3076.209662,2955.294285,2836.232408,2718.981737,2603.501256,2489.751177
22,3204.675260,3081.750557,2960.725755,2841.580924,2724.225767,2608.666400,2494.839201
23,3210.332411,3087.319919,2966.185190,2846.933153,2729.496828,2613.858141,2499.930663
24,3215.993619,3092.868682,2971.648462,2852.312912,2734.771522,2619.030335,2505.025564
25,3221.658887,3098.421378,2977.115576,2857.672594,2740.049851,2624.206052,2510.123910
26,3227.303238,3104.002605,2982.586535,2863.036002,2745.331821,2629.408425,2515.225704
27,3232.976624,3109.563194,2988.061344,2868.426999,2750.617434,2634.614359,2520.330949
28,3238.654084,3115.152359,2993.540006,2873.797884,2755.906695,2639.800698,2525.439648
29,3244.335622,3120.720859,2999.022526,2879.196399,2761.199607,2645.013750,2530.551805
30,3250.021244,3126.317978,3004.508908,2884.598689,2766.519722,2650.207183,2535.690270
31,3255.710953,3131.894406,3009.999155,2889.980826,2771.819964,2655.427368,2540.809369
32,3261.404754,3137.499496,3015.493273,2895.390657,2777.123869,2660.651134,2545.931938
33,3267.127761,3143.108586,3021.015600,2900.804273,2782.431440,2665.878483,2551.080870
34,3272.829777,3148.696946,3026.517487,2906.221679,2787.766295,2671.109420,2556.210402
35,3278.535897,3154.314034,3032.023256,2911.642877,2793.081226,2676.343947,2561.343413
36,3284.246128,3159.935135,3037.557299,2917.043860,2798.399835,2681.582069,2566.502846
37,3289.985654,3165.560254,3043.070862,2922.472640,2803.745789,2686.823790,2571.642842
38,3295.704135,3171.189396,3048.612742,2927.905225,2809.071782,2692.069112,2576.809297
39,3301.426739,3176.822564,3054.134115,2933.341619,2814.425160,2697.318041,2581.979278
40,3307.178707,3182.459763,3059.683848,2938.805906,2819.782264,2702.570579,2587.129786
41,3312.909588,3188.100998,3065.213049,2944.249948,2825.119370,2707.826730,2592.306811
42,3318.669879,3193.746272,3070.770653,2949.697810,2830.483921,2713.086498,2597.487372
43,3324.434347,3199.395590,3076.307697,2955.149498,2835.852210,2718.373288,2602.671472
44,3330.177686,3205.048956,3081.873188,2960.605014,2841.224241,2723.640318,2607.836051
45,3335.950505,3210.706375,3087.442637,2966.088529,2846.576222,2728.910975,2613.027224
46,3341.727514,3216.392800,3093.016048,2971.551734,2851.955732,2734.208714,2618.221948
47,3347.483353,3222.058355,3098.593427,2977.018779,2857.338994,2739.486656,2623.420225
48,3353.268739,3227.727976,3104.150180,2982.513886,2862.726014,2744.791719,2628.622060
49,3359.058330,3233.426670,3109.735488,2987.988644,2868.116796,2750.076960,2633.827456

In [102]:
def read_files(path):
    files = sorted([i for i in os.listdir(path) if '.txt' in i and 'ps' not in i and 'powers' not in i])
    
    data = [i for i in files if '_bg' not in i]
    data_indices = [str(i) for i in np.arange(len(data))]
    
    bkg = [i for i in files if '_bg' in i]
    bkg_indices = [str(i) for i in np.arange(len(bkg))]
    
    col_names = ['wl','1','2','cts']
    
    df_data = pd.DataFrame()
    for i in data:
        df = pd.read_csv(path+'/'+i, sep='\t', names=[i.rstrip('.txt')+'wl','1','2',i.rstrip('.txt')+'cts'])
        df.drop(columns=['1','2'])
        df[i.rstrip('.txt')+'wn'] = 10000000/df[i.rstrip('.txt')+'wl'] - 12579
        df.sort_values(by=i.rstrip('.txt')+'wn',inplace=True)
        pd.merge(df_data,df,how='right')
        
    return df_data
read_files(path)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [81]:
read_files(path)

['2600.txt',
 '2600_bg.txt',
 '2700.txt',
 '2800.txt',
 '2800_bg.txt',
 '2900.txt',
 '3000.txt',
 '3000_bg.txt',
 '3100.txt',
 '3100_bg.txt',
 '3200.txt',
 '3300.txt',
 '3300_bg.txt',
 '3400.txt',
 '3500.txt',
 '3500_bg.txt',
 '3600.txt',
 '3700.txt',
 '3700_bg.txt']

In [61]:
df1 = pd.read_csv(path+'/2600.txt', sep='\t', names=['wl','1','2','cts'])
df1['wn'] = 10000000/df1['wl'] - 12579
df1.sort_values(by='wn',inplace=True)

In [60]:
df2 = pd.read_csv(path+'/3700.txt', sep='\t', names=['wl','1','2','cts'])
df2['wn'] = 10000000/df2['wl'] - 12579
df2.sort_values(by='wn', inplace=True)

In [62]:
df1

          wl  1  2   cts           wn
163  638.543  1  1   615  3081.652454
162  638.317  1  1   615  3087.197203
161  638.091  1  1   610  3092.745880
160  637.865  1  1   613  3098.298488
159  637.639  1  1   616  3103.855032
..       ... .. ..   ...          ...
4    602.099  1  1   791  4029.564372
3    601.867  1  1   782  4035.966429
2    601.634  1  1   837  4042.401051
1    601.401  1  1   982  4048.840659
0    601.168  1  1  1177  4055.285258

[164 rows x 5 columns]

In [63]:
df2

          wl  1  2   cts           wn
163  668.316  1  1  4888  2383.981584
162  668.093  1  1  4593  2388.976015
161  667.870  1  1  4423  2393.973782
160  667.647  1  1  4049  2398.974888
159  667.424  1  1  3958  2403.979335
..       ... .. ..   ...          ...
4    632.306  1  1   665  3236.127486
3    632.076  1  1   657  3241.882299
2    631.846  1  1   614  3247.641302
1    631.616  1  1   589  3253.404499
0    631.386  1  1   605  3259.171895

[164 rows x 5 columns]